#!/usr/bin/env bash

# Carrega o tema

THEME_DWM="$HOME/.theme_selected"

if [ -f "$THEME_DWM" ]; then
    source ~/.$THEME_DWM
else
    THEME_GTK="Nordic-darker-v40"
    THEME_ICON="Zafiro-Nord-Black"
    THEME_MODE="Nord"
    COLOR_MODE="Dark"
    THEME_ICON_DUNST="/usr/share/icons/Papirus-Dark/"
    GTK_PREFER_DARK_MODE="1"
    EMACS_THEME="doom-nord"
    WALLPAPER_LIGHTDM="ign_unsplash15.png"
    COLOR_BACKGROUND="#2e3440"
    COLOR_BACKGROUND2="#3b4252"
    COLOR_TEXT="#d8dee9"
    COLOR_1="#ebcb8b"
    COLOR_2="#d08770"
    COLOR_3="#bf616a"
    COLOR_4="#b48ead"
    COLOR_5="#81a1c1"
    COLOR_6="#88c0d0"
    COLOR_7="#a3be8c"
    COLOR_8="#4c566a"
    COLOR_9="#f5e5bc"
    COLOR_10="#e5a28a"
    COLOR_11="#d97782"
    COLOR_12="#c9a5c7"
    COLOR_13="#a8c7e0"
    COLOR_14="#a0d5e0"
    COLOR_15="#c3d8b1"
    COLOR_16="#6d798c"
fi



# Carrega informacoes do modo de operacao
arquivo_modo="$HOME/.cache/dwmblocks_modo_operacao"

if [ -f "$arquivo_modo" ]; then
    source "$arquivo_modo"
    theme_type="$THEME"
else
    OPERATION_MODE="COMPLETO"
    theme_type="icon-color"
fi

#theme_type="separador"

aplicar_tema() {
    local icone="$1"
    local conteudo="$2"
    local cor_forte="$3"
    local cor_fraca="$4"

    if [ "$icone" == "" ] && [ "$conteudo" == ""  ]; then
        echo ""
    else

        case "$theme_type" in
            "colorfull")
                echo "^b$cor_forte^^c$COLOR_BACKGROUND^ $icone ^d^^c$COLOR_BACKGROUND^^b$cor_fraca^ $conteudo ^d^ "
                ;;
            "colorfull-icon")
                echo "^b$cor_forte^^c$COLOR_BACKGROUND^ $icone ^d^^c$COLOR_TEXT^ $conteudo ^d^ "
                ;;
            "brackets")
                echo "[^b$COLOR_BACKGROUND^^c$cor_forte^$icone^d^^b$COLOR_BACKGROUND^^c$cor_fraca^ $conteudo^d^] "
                ;;
            "rounded")
                echo "(^b$COLOR_BACKGROUND^^c$cor_forte^$icone^d^^b$COLOR_BACKGROUND^^c$cor_fraca^ $conteudo^d^) "
                ;;
            "keys")
                echo "{^b$COLOR_BACKGROUND^^c$cor_forte^$icone^d^^b$COLOR_BACKGROUND^^c$cor_fraca^ $conteudo^d^} "
                ;;
            "simple")
                echo " ^b$COLOR_BACKGROUND^^c$COLOR_TEXT^$icone $conteudo^d^ "
                ;;
            "simple-color")
                echo " ^b$COLOR_BACKGROUND^^c$cor_forte^$icone $conteudo^d^ "
                ;;
            "icon-color")
                echo " ^b$COLOR_BACKGROUND^^c$cor_forte^$icone^d^^b$COLOR_BACKGROUND^^c$COLOR_TEXT^ $conteudo^d^ "
                ;;
            "separador")
				echo "| ^b$COLOR_BACKGROUND^^c$cor_forte^$icone^d^^b$COLOR_BACKGROUND^^c$cor_fraca^ $conteudo^d^ "
				;;
        esac

    fi
}
